# Generated by Django 4.2.7 on 2024-01-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionsmodel',
            name='tuition_types',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
