# Generated by Django 4.2.7 on 2024-01-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0002_alter_tuitionsmodel_tuition_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionsmodel',
            name='cls',
            field=models.ManyToManyField(to='tuitions.userclassmodel'),
        ),
    ]
