# Generated by Django 4.2.7 on 2024-01-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0004_remove_tuitionsmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionsmodel',
            name='cls',
        ),
        migrations.AddField(
            model_name='tuitionsmodel',
            name='cls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuitions.userclassmodel'),
        ),
    ]
