# Generated by Django 4.2.7 on 2024-01-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0007_rename_image_tuitionsmodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionsmodel',
            name='img',
        ),
        migrations.AddField(
            model_name='tuitionsmodel',
            name='books_img',
            field=models.ImageField(blank=True, null=True, upload_to='tuitions/media/uploads/'),
        ),
        migrations.AddField(
            model_name='tuitionsmodel',
            name='is_apply',
            field=models.BooleanField(default=False),
        ),
    ]
