# Generated by Django 4.2.7 on 2024-01-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0008_remove_tuitionsmodel_img_tuitionsmodel_books_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='tuition',
        ),
        migrations.RemoveField(
            model_name='tuitionsmodel',
            name='books_img',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
