# Generated by Django 4.2.7 on 2024-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0010_reviewmodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionsmodel',
            name='books_img',
            field=models.ImageField(blank=True, null=True, upload_to='tuitions/media/uploads/'),
        ),
    ]
