# Generated by Django 4.2.7 on 2024-01-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0011_tuitionsmodel_books_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
